# Bun configuration for the federated modules monorepo

[install]
# Bun workspaces configuration
# Automatically installs dependencies for all workspace packages
auto = "auto"

# Registry configuration
registry = "https://registry.npmjs.org/"

# Cache directory
[install.cache]
dir = ".bun-cache"

[install.scopes]
# Scoped package configurations if needed
# "@config" = "https://registry.npmjs.org/"

[test]
# Test runner configuration (Bun can run Jest tests)
# Coverage settings
coverage = true
coverageReporter = [ "text", "lcov", ]

# Exclude assets from coverage across the monorepo
coveragePathIgnorePatterns = [
	"**/assets/**",
  "**/@config/**",
  "**/types/**",
]

# Ensure DOM globals exist, then run unified setup (matchers + cleanup)
preload = [
	"@config/bun-test-config/happydom.ts",
	"@config/bun-test-config/setup-tests.ts",
	"@config/bun-test-config/testing-library.ts"
]

[build]
# Build configuration for TypeScript/JSX
target = "browser"
format = "esm"

# Source map generation
sourcemap = "external"

# Minification in production
minify = true
