[test]

coverage = true

coveragePathIgnorePatterns = [
  "**/@config/**",
  "**/types/**",
]
# Ensure DOM globals exist, then run unified setup (matchers + cleanup)
preload = [
  "@config/bun-test-config/happydom.ts",
  "@config/bun-test-config/setup-tests.ts",
  "@config/bun-test-config/testing-library.ts"
]
