[test]
coverage = true
coverageReporter = [ "text", "lcov", ]

coveragePathIgnorePatterns = [
  "**/@config/**",
  "**/types/**",
  "**/__mocks__/**",
]

# Ensure DOM globals exist, then run unified setup (matchers + cleanup)
preload = [
  "@config/bun-test-config/happydom.ts",
  "@config/bun-test-config/setup-tests.ts",
  "@config/bun-test-config/testing-library.ts",
  "./src/__mocks__/shared-modules.ts"
]
